ansible/group_vars/brb/instanc_cfg.yml
ansible/group_vars/nbc/instanc_cfg.yml

- creates an new env var GLOBAL_ANNOUNCEMENT_ADMIN_TEACHER
- here it can store a text / html which it will be visible for admin and teacher only on all pages on top (legacy client only)
- https://ticketsystem.schul-cloud.org/browse/SC-9148
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2609
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

added GLOBAL_ANNOUNCEMENT_ADMIN_TEACHER variable

---

ansible/group_vars/brb/instanc_cfg.yml
ansible/group_vars/nbc/instanc_cfg.yml

fix broken yaml quotes

---

ansible/roles/dof_mongo/tasks/main.yml
ansible/roles/dof_mongo/templates/deployment.yml.j2
ansible/roles/dof_mongo/templates/pvc.yml.j2

Add an PVC to monog
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2613

OPS- 2613 - add PVC to monog

---

ansible/roles/dof_rabbitmq/tasks/main.yml
ansible/roles/dof_rabbitmq/templates/configmap.yml.j2
ansible/roles/dof_rabbitmq/templates/configmap_files.yml.j2
ansible/roles/dof_rabbitmq/templates/deployment.yml.j2
ansible/roles/dof_rabbitmq/templates/pvc.yml.j2

add test
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2617

OPS-2617 - add pvc to RabitMQ Deployment

---

ansible/roles/dof_redis/tasks/main.yml
ansible/roles/dof_redis/templates/deployment.yml.j2
ansible/roles/dof_redis/templates/pvc.yml.j2

add pvc
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2616

OPS-2616 - add pvc to redis

---

ansible/roles/dof_postgresql/tasks/main.yml
ansible/roles/dof_postgresql/templates/configmap.yml.j2
ansible/roles/dof_postgresql/templates/deployment.yml.j2
ansible/roles/dof_postgresql/templates/pvc.yml.j2

add pvc
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2615

OPS-2615 - add pvc to PostgreSQL

---

ansible/group_vars/brb/instance_cfg.yml

To align test and prod, SC_CONTACT_EMAIL variable was added.
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1849
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2622
- https://ticketsystem.schul-cloud.org/browse/SC-9221

added environment variable for brb

---

.github/workflows/clean.yml
.github/workflows/deploy.yml
ansible/playbook.yml

Add Antivirus Check Service
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2496
Add Antivirus Check Service

OPS-2496 - add antivirus check service

---

LICENSE

Add AGPLv3 as license
Add AGPLv3 as license

Add AGPLv3 as license

---

ansible/roles/ingress/templates/ingress.yml.j2

https://ticketsystem.hpi-schul-cloud.org/browse/BC-144
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9083

BC-144 Add ingress route for new school admin page

---

ansible/roles/storage/templates/deployment.yml.j2

Change the update strategy for storage to recreate.
Change the update strategy for storage to recreate.

Change the update Strategy for storage to recreate

---

ansible/playbook.yml
ansible/roles/ingress/tasks/main.yml
ansible/roles/ingress/templates/default-backend-404-configmapfile.yml.j2
ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2
ansible/roles/ingress/templates/default-backend-404-svc.yml.j2
ansible/roles/ingress/templates/ingress.yml.j2

Add a Default 404 Backend so that the Ingress-Controller is Happyer
https://ticketsystem.hpi-schul-cloud.org/browse/BC-148
Add a Default 404 Backend so that the Ingress-Controller is Happyer

BC-148 - Default 404 Backend Ingress

---

ansible/roles/dof_rabbitmq/templates/rabbitmq.yaml.j2
ansible/roles/ingress/templates/ingress.yml.j2
sc-common/sc-clamav-deployment.yml
sc-common/sc-clamav-svc.yml

removed fileStorage/securityCheck from ingress

BC-110 added calmav to sc-common

---

ansible/roles/hydra/tasks/main.yml
ansible/roles/hydra/templates/job.yml.j2

I hat forgetten that Docker image chanings, kubernetes jobs have trouble with it.
This fix it.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-53
Delete the old hydra migrate job, before creating the new one.

BC-53 - Rollfixes

---

ansible/roles/ingress/templates/ingress.yml.j2

BC-179 - update task routes

---

ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/default/instance_cfg.yml
ansible/group_vars/nbc/instance_cfg.yml

BC-280 - enabled edusharing

---

ansible/roles/ingress/templates/ingress.yml.j2

added favicon path for nuxt

---

ansible/roles/ingress/templates/ingress.yml.j2

- https://ticketsystem.hpi-schul-cloud.org/browse/BC-252

Feature/BC-252 - add ingress route for rooms-overview

---

ansible/roles/ingress/templates/ingress.yml.j2

- server api route added for rooms-overview

added server api route for rooms-overview

---

ansible/roles/ingress/templates/ingress.yml.j2

bc-258 - remove deprecated path

---

ansible/roles/ingress/templates/ingress.yml.j2

The legacy wopi route can be closed, when the client pr https://github.com/hpi-schul-cloud/schulcloud-client/pull/2681 is published.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-170

BC-170 BC-366 close legacy wopi uri

---

.github/workflows/clean_branches.yml
.github/workflows/push.yml

Add auto deployment for branches of configuration change
https://ticketsystem.hpi-schul-cloud.org/browse/BC-658
https://ticketsystem.hpi-schul-cloud.org/browse/BC-589
Add auto deployment for branches of configuration change

BC-589 - BC-658 - Add auto deployment for branches of configuration change

---

ansible/roles/ingress/templates/ingress.yml.j2

- https://github.com/hpi-schul-cloud/nuxt-client/pull/1966

BC-724 - add ingress route for listing room elements

---

ansible/roles/ingress/templates/ingress.yml.j2

BC-724 - Fix formating issue

---

ansible/roles/ingress/templates/ingress.yml.j2

https://ticketsystem.hpi-schul-cloud.org/browse/BC-724

BC-724 - backend api root for courses

---

ansible/group_vars/all/dof_etherpad.yml
ansible/roles/dof_etherpad/templates/configmap.yml.j2
ansible/roles/dof_etherpad/templates/secret.yml.j2

bc-879 update etherpad to 1.8.16

---

.github/workflows/clean_workflow.yml
.github/workflows/deploy.yml
ansible/group_vars/all/edtrio.yml
ansible/group_vars/all/schulcloud-editor.yml
ansible/playbook.yml
ansible/roles/edtrio/tasks/main.yml
ansible/roles/edtrio/templates/configmap.yml.j2
ansible/roles/edtrio/templates/deployment.yml.j2
ansible/roles/edtrio/templates/svc.yml.j2
ansible/roles/schulcloud-editor/tasks/main.yml
ansible/roles/schulcloud-editor/templates/configmap.yml.j2
ansible/roles/schulcloud-editor/templates/deployment.yml.j2
ansible/roles/schulcloud-editor/templates/onepassword.yml.j2
ansible/roles/schulcloud-editor/templates/secret.yml.j2
ansible/roles/schulcloud-editor/templates/svc.yml.j2

Sort and split ansible rols
hpi-schul-cloud/nuxt-client#1986
hpi-schul-cloud/schulcloud-server#3233
hpi-schul-cloud/schulcloud-client#2730
hpi-schul-cloud/schulcloud-calendar#99
hpi-schul-cloud/superhero-dashboard#147
hpi-schul-cloud/antivirus_check_service#16
https://ticketsystem.hpi-schul-cloud.org/browse/BC-741

BC-741 - Sort and split ansible rols

---

ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/default/instance_cfg.yml
ansible/group_vars/develop/cfg.yml
ansible/group_vars/international/instance_cfg.yml
ansible/group_vars/nbc/instance_cfg.yml
ansible/host_vars/ref-brb/cfg.yml
ansible/host_vars/ref-dbildungscloud/cfg.yml
ansible/host_vars/ref-int/cfg.yml
ansible/host_vars/ref-nbc/cfg.yml
ansible/host_vars/ref-thr/cfg.yml

As a user, I want to be directed to the new status page when I click the link "Status" in the footer.
Config cleanup.
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/BC-999
Client-PR: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2739 
Nuxt-PR: https://github.com/hpi-schul-cloud/nuxt-client/pull/2013
Server-PR: https://github.com/hpi-schul-cloud/schulcloud-server/pull/3259
CONFIG CLEANUP:
Server-PR: https://github.com/hpi-schul-cloud/schulcloud-server/pull/3267
- environment variable set to default (dBildungscloud) and individually set for each instance
ALERT_STATUS_URL: https://status.INSTANCE.de
More and detailed information on the *definition of done* can be found …

BC-999 update status pages

---

ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/default/instance_cfg.yml
ansible/group_vars/develop/cfg.yml

BC-1084 no default value for ALERT_STATUS_URL

---

ansible/roles/ingress/templates/ingress.yml.j2

https://ticketsystem.hpi-schul-cloud.org/browse/BC-1064

BC-1064: add ingress route for rooms page

---

ansible/roles/ingress/templates/ingress.yml.j2

- adding a new api endpoint for rooms page
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1064

add api endpoint

---

ansible/group_vars/all/x_ingress.yml

- Adding api/v3/rooms api into x_ingress file

adding rooms api into x_ingress

---

ansible/roles/dof_etherpad/tasks/main.yml
ansible/roles/dof_etherpad_nginx/tasks/main.yml
ansible/roles/dof_mongo/tasks/main.yml
ansible/roles/dof_postgresql/tasks/main.yml
ansible/roles/dof_rabbitmq/tasks/main.yml
ansible/roles/edtrio/tasks/main.yml
ansible/roles/hydra/tasks/main.yml
ansible/roles/libreoffice/tasks/main.yml
ansible/roles/rocketchat/tasks/main.yml
ansible/roles/schulcloud-editor/tasks/main.yml
ansible/roles/storage/tasks/main.yml

Change the mode for the configmaps at the ansible roles to apply for configmaps and secrets
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1230
hpi-schul-cloud/antivirus_check_service#20
hpi-schul-cloud/superhero-dashboard#157
hpi-schul-cloud/schulcloud-server#3311
hpi-schul-cloud/schulcloud-client#2759
hpi-schul-cloud/schulcloud-calendar#109
hpi-schul-cloud/nuxt-client#2040

BC-1230 - change mode for configmaps to apply

---

ansible/group_vars/all/config.yml
ansible/group_vars/all/x_ingress.yml

https://ticketsystem.hpi-schul-cloud.org/browse/BC-1138

BC-1138 activate course share for nuxt

---

ansible/group_vars/brb/smtp.yml
ansible/group_vars/default/smtp.yml
ansible/group_vars/international/smtp.yml
ansible/group_vars/nbc/smtp.yml
ansible/group_vars/thr/smtp.yml

add for all instance groups the SMTP_SENDER
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1284

BC-1284 - add for all instance groups the SMTP_SENDER

---

ansible/group_vars/all/x_ingress.yml

add /api/v1/consentVersions
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1299

BC-1299 - add /api/v1/consentVersions

---

ansible/group_vars/brb/instance_cfg.yml
ansible/host_vars/ref-brb/cfg.yml

allow the roster
https://ticketsystem.schul-cloud.org/browse/bc-1157

BC-1157 - allow the roster path for ref-brb

---

ansible/host_vars/ref-audit/cfg.yml

fix Audit login
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1154

BC-1154 - fix Audit login

---

ansible/group_vars/all/config.yml

Cherry pick of https://github.com/hpi-schul-cloud/dof_app_deploy/commit/8b4cf55276c74a75251be2143ff81858ad44b708

BC-1138 - fix var set wrongly on wrong feature flag (#130)

---

.github/workflows/rollout.yml
ansible/hosts

* Deactivate ref-nbc, so long it not be deployed with this
* BC-1156 - Fix missing ref-thr at hosts files

Fix Errors for the Deployment (#136)

---

ansible/host_vars/default_host/with.yml
ansible/host_vars/ref-thr/with.yml
ansible/playbook.yml
ansible/playbook_rollout.yml

Reaktivate the TSP Sync 
hpi-schul-cloud/schulcloud-server#3334
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1335

BC-1335 - fix tsp sync

---

ansible/group_vars/all/config.yml

Activete Alerts ( status ) for all Instances

Activete Alerts ( status ) for all Instances

---

ansible/group_vars/all/config.yml

Cherry pick for Activete Alerts ( status ) for all Instances (#141) to get it to main

Activete Alerts ( status ) for all Instances (#141)

---

ansible/roles/dof_mongo/tasks/main.yml
ansible/roles/dof_postgresql/tasks/main.yml

Fix Ansible roles for mongo and postgreSQL.

Fix Ansible roles for mongo and postgreSQL

---

ansible/roles/dof_mongo/tasks/main.yml
ansible/roles/dof_postgresql/tasks/main.yml

Fix the Ansible roles for mongo and postgreSQL

Fix Ansible roles for mongo and postgreSQL. (#164)

---

.github/workflows/rollout.yml

Remove NBC Deployment Jobs form release 27.8

remove NBC from this round of release

---

.github/workflows/rollout.yml
ansible/group_vars/all/config.yml
ansible/hosts

Fix missing parts for thueringia
Fix missing only skip if stage before fail

Fix missing parts at 27.9

---

ansible/host_vars/ref-nbc/cfg.yml
ansible/host_vars/ref-nbc/libreoffice.yml

move the URL Change for staging niedersachsen to main

Change URL for staging niedersachsen

---

ansible/roles/libreoffice/templates/deployment.yml.j2

Fix LibreOffice CPU

---

ansible/group_vars/all/config.yml
ansible/group_vars/all/x_ingress.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-1460
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3394
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2113

feature/BC-1460: invite course ingress

---

.github/workflows/rollout.yml

Add output for Targets
Output Target Host, Group, Stage or all.
https://ticketsystem.dbildungscloud.de/browse/BC-1611

BC-1611 - add output for Targets

---

.github/workflows/host.yml

add selection by deploy stage
https://ticketsystem.dbildungscloud.de/browse/BC-1610

BC-1610 - add selection by deploy stage

---

.github/workflows/rollout.yml

Add more informations about what trigger the deployment
https://ticketsystem.dbildungscloud.de/browse/BC-1611
https://github.com/hpi-schul-cloud/dof_app_deploy/runs/5969044525?check_suite_focus=true

BC-1611 - Add more informations about what triggered the deployment

---

ansible/group_vars/nbc/instance_cfg.yml

set SC_CONTACT_EMAIL  for nbc
https://ticketsystem.dbildungscloud.de/browse/BC-1668

BC-1668 - set SC_CONTACT_EMAIL  for nbc

---

ansible/group_vars/all/x_ingress.yml

https://ticketsystem.dbildungscloud.de/browse/BC-1464
https://github.com/hpi-schul-cloud/nuxt-client/pull/2143

BC-1464- Adding homework api route

---

.github/workflows/rollout.yml

Remove demo from the code base
hpi-schul-cloud/schulcloud-client#2842
hpi-schul-cloud/schulcloud-server#3431
hpi-schul-cloud/nuxt-client#2147
https://ticketsystem.dbildungscloud.de/browse/BC-1370

BC-1370 - remove demo from the code base

---

ansible/group_vars/all/config.yml

BC-1737 - limit WOPI downloadable file size
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3462

BC-1737 - limit WOPI downloadable file size

---

ansible/group_vars/all/config.yml

removed comma

---

ansible/group_vars/all/config.yml
ansible/roles/ingress/templates/ingress.yml.j2

BC-2037 - Add request body size for new files storage service

---

ansible/group_vars/develop/erwin-idm.yml
ansible/roles/erwin-idm/README.MD

Upgrading keycloak to version 18.0.2.
https://ticketsystem.dbildungscloud.de/browse/EW-234
The erwin-idm image was updated.

EW-234 Keycloak upgrade to v18

---

ansible/group_vars/all/config.yml

To provide further information for our users (teachers and admins) we want to display the blue status bar as in [SC-9148](https://ticketsystem.dbildungscloud.de/browse/SC-9148) (display blue status bar on dashboard page for SJW help) again.
BC-2184

BC-2184 - Display blue status bar for SJW 2022

---

ansible/group_vars/all/config.yml
ansible/group_vars/nbc/instance_cfg.yml
ansible/host_vars/nbc_host/cfg.yml
ansible/host_vars/prod-nbc/cfg.yml
ansible/host_vars/ref-nbc/cfg.yml

Added env NEXTCLOUD_SOCIALLOGIN_OIDC_INTERNAL_NAME, COLLABORATIVE_STORAGE_PROVIDER and moved FEATURE_NEXTCLOUD_TEAM_FILES_ENABLED to group_vars because it is activated in all instances of nbc.
https://ticketsystem.dbildungscloud.de/browse/N21-207
NEXTCLOUD_SOCIALLOGIN_OIDC_INTERNAL_NAME=SchulcloudNextcloud
COLLABORATIVE_STORAGE_PROVIDER=Nextcloud

N21-207 Added env for nextcloud

---

ansible/group_vars/all/config.yml
ansible/roles/storage/templates/ingress.yml.j2
ansible/roles/storage/templates/pvc.yml.j2

When executing a copy-process with many files and entities the copy process might exceed the existing timeout. Therefore this was increased.
https://ticketsystem.dbildungscloud.de/browse/BC-2137
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3581

BC-2137 - copy files embedded in texts

---

ansible/roles/erwin-idm/templates/configmap-init.yml.j2

The curl version had changed due to some [changes](https://github.com/hpi-schul-cloud/infra-tools/commit/379506c1f9522dc5f36afc71945e51710c06a86e#) within infra-tools (from v7.74 to v7.68). As a result, some curl options were no longer supported, causing curl to stop working. To fix this, the curl option '--retry-all-errors' was removed and replaced with '--retry-connrefused'.
https://ticketsystem.dbildungscloud.de/browse/EW-305
Removed the curl option '--retry-all-errors' and replaced it with '--retry-connrefused'.

EW-305 set curl option --retry-connrefused

---

ansible/group_vars/all/config.yml

To make the copy function not visible in the legacy page of a course we deactivate the variable for the legacy client.
BC-2315

BC-2315 - remove legacy copy function from room view

---

ansible/host_vars/prod-nbc/cfg.yml

due to the release date of 23.8.2022 of the waiting room feature in prod on nbc, here the env var changes for that

N21-182 bbb waiting room now set to true in all nbc instances

---

ansible/group_vars/all/config.yml

https://ticketsystem.dbildungscloud.de/browse/BC-2360

BC-2360 fix missing env var OIDCMOCK

---

ansible/group_vars/all/x_ingress.yml

BC-1513 Add lessons ingress

---

ansible/group_vars/all/x_ingress.yml

Add new sharetoken endpoint to ingress routes to enable course sharing.
https://ticketsystem.dbildungscloud.de/browse/BC-2472

BC-2472 - Implement course sharing

---

ansible/group_vars/all/x_ingress.yml

BC-2362
https://github.com/hpi-schul-cloud/nuxt-client/pull/2273

BC-2362 - Open api alert route for nuxt

---

ansible/group_vars/all/config.yml

to remove the blue status bar the text value needs to be removed
BC-2156
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3690

BC-2156 - SJW - Disable Transfer Period in all instances

---

ansible/roles/maildrop/templates/deployment.yml.j2

BC-2709 set smtp timeouts in maildrop

---

.github/workflows/deploy.yml

https://ticketsystem.dbildungscloud.de/browse/BC-2684

BC-2684 resolve annoying warning when branch does not exist

---

ansible/group_vars/all/config.yml

remove out of place env vars

---

ansible/group_vars/all/x_ingress.yml
ansible/playbook_rollout.yml

BC-2757 ingress rule for version aggregator

---

ansible/group_vars/all/config.yml
ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/thr/instance_cfg.yml

Add env variables for bbb presentation (required for https://github.com/hpi-schul-cloud/schulcloud-server/pull/3789)
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/414
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3789
- https://ticketsystem.dbildungscloud.de/browse/BC-690
- Added env variables for bbb presentation

BC-690 Add env variables for bbb presentation

---

ansible/group_vars/all/x_ingress.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-1508
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3780

BC-1508 - add ingress for submissions

---

ansible/group_vars/all/config.yml

Add feature flag to manage IDM usage as account storage.
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3732
New feature flag `FEATURE_IDENTITY_MANAGEMENT_STORE_ENABLED`, which defaults to `false`.
NA
See changes.
NA
NA

EW-127 Add feature flag for IDM store.

---

.github/workflows/test.yml
.gitignore
ansible/group_vars/all/config.yml
tests/test.py

https://ticketsystem.dbildungscloud.de/browse/BC-2785

BC-2785 tests

---

ansible/group_vars/all/x_ingress.yml

We need a new ingress entry so that the nuxt client can call the v3 tools api.
https://ticketsystem.dbildungscloud.de/browse/N21-542

N21-542 add ingress entry for v3 tools

---

ansible/group_vars/all/config.yml

Adding default value for `FEATURE_USE_LOGIN_ENDPOINTS_V3`.
- https://ticketsystem.dbildungscloud.de/browse/EW-443
Does not apply.
Does not apply.
Does not apply.
Does not apply.
Does not apply.

EW-443 Hotfix

---

ansible/roles/mongodb_query_exporter/defaults/main.yaml

BC-3166 do not create service accoutns for mongodb exporter

---

ansible/group_vars/all/config.yml

Enable new login routes, by reverting "EW-443 Hotfix"; implicitly enables 'FEATURE_USE_LOGIN_ENDPOINTS_V3'. Must not be applied before https://github.com/hpi-schul-cloud/schulcloud-server/pull/3878 is merged, which fixes the original LDAP login issue.
https://ticketsystem.dbildungscloud.de/browse/EW-443
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3878
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/451
See description
NA
Implicitly enables 'FEATURE_USE_LOGIN_ENDPOINTS_V3'
NA
NA

EW-443 Re-enable new login routes

---

ansible/playbook_rollout.yml

Add ErWIn IDM to the roll-out script. This completes https://github.com/hpi-schul-cloud/dof_app_deploy/pull/428
https://ticketsystem.dbildungscloud.de/browse/EW-460
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/428
See description
NA
Roll-out is extend and includes ErWIn IDM.
NA
NA

EW-460 Add ErWIn IDM to roll out

---

ansible/roles/rocketchat/templates/deployment.yml.j2

BC-3115 Change ports of RocketChat probes

---

ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/default/instance_cfg.yml
ansible/group_vars/nbc/instance_cfg.yml

Ops 4289 use ionos vm edusharing on dev

---

ansible/host_vars/prod-dbc/cfg.yml

BC-3271 - disable matrix messenger on prod dbc

---

ansible/group_vars/all/config.yml
ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/default/instance_cfg.yml

Implement new env vars for role specific status infos for federal states.
BC-3152
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3115
- GLOBAL_ANNOUNCEMENT_TEXT will set the text of the status which will be shown to the roles set in the (array) GLOBAL_ANNOUNCEMENT_ROLES

BC-3152 - Display blue status bar info

---

ansible/group_vars/all/config.yml

https://github.com/hpi-schul-cloud/schulcloud-server/pull/3961
https://ticketsystem.dbildungscloud.de/browse/BC-3444

BC-3444 - enhance user data with information on last sync date

---

ansible/roles/ingress/templates/ingress.yml.j2

The header size of the request is too big. Nginx throws away the Location header, resulting in the 502 Bad Gateway. In the new release, the state was added, which broke the camel's back.
The temporary solution is to increase the header size in nginx.
https://ticketsystem.dbildungscloud.de/browse/BC-3606

BC-3606 Increased nginx header size

---

ansible/group_vars/all/config.yml

change grace period to 14 days.
https://ticketsystem.dbildungscloud.de/browse/N21-654

N21-654 change grace period to 14 days

---

.github/workflows/clean.yml
.github/workflows/clean_branches.yml
.github/workflows/clean_workflow.yml
.github/workflows/deploy.yml
.github/workflows/dispatch.yml
.github/workflows/push.yml

https://ticketsystem.dbildungscloud.de/browse/BC-4009

BC-4009 removing unused TOKEN_INVENTORY variable

---

ansible/group_vars/all/config.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-3146
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4086
Add limit variables for TSP School Sync

BC-3146 Add limit variables for TSP School Sync

---

ansible/roles/rocketchat/templates/fixup-configmap.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-4215

BC-4215 mongo->mongosh in script

---

ansible/host_vars/ref-nbc/cfg.yml

Deactivates ctl tab on staging
https://ticketsystem.dbildungscloud.de/browse/N21-972

N21-972 deactivates ctl tab on stage

---

ansible/host_vars/prod-brb/cfg.yml

Enable Nextcloud for Prod Brandenburg
In addition to setting the Feature Flag "FEATURE_NEXTCLOUD_TEAM_FILES_ENABLED" to true, a Tool entry has to get added in the SuperHeroDashboard. To the user role in SHD also NEXTLOUD_USER has to get added. Both has been done and connection works.
This Feature Flags makes the Nextcloud Button appear in the Schulcloud.
https://ticketsystem.dbildungscloud.de/browse/BC-4269
https://ticketsystem.dbildungscloud.de/browse/OPS-4842

OPS-4842-Enable-Nextcloud-Prod-Brandenburg

---

ansible/group_vars/all/config.yml

https://ticketsystem.dbildungscloud.de/browse/BC-4323

BC-4323 add ROOT_URL_REDIRECT to ansible/group_vars/all/config.yml

---

ansible/group_vars/all/config.yml
ansible/group_vars/develop/cfg.yml

https://ticketsystem.dbildungscloud.de/browse/BC-4340

BC-4340 enablding metrics for ref and prod

---

ansible/group_vars/all/config.yml
ansible/group_vars/default/instance_cfg.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-4292
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4217

set column board help links

---

ansible/host_vars/ref-nbc/cfg.yml

enable ctl tools tab in staging
https://ticketsystem.dbildungscloud.de/browse/N21-1026

N21-1026 enable ctl tools tab in staging

---

ansible/group_vars/all/config.yml
ansible/group_vars/develop/cfg.yml

Even if the code should stay for now, the user should not be able to see any content for beta tasks anymore.
For that, we need to remove seting the env var to anything else then the default `false` in the server code.
BC-4447
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4226
- remove seting the env var (will be set as default in server)

BC-4447 - Remove beta task from user interface

---

ansible/group_vars/all/x_ingress.yml

- add videoconference2 to ingress
https://ticketsystem.dbildungscloud.de/browse/N21-881
https://github.com/hpi-schul-cloud/nuxt-client/pull/2623

N21-881 Add videoconference2 to ingress

---

ansible/group_vars/all/x_ingress.yml

https://github.com/hpi-schul-cloud/dof_app_deploy/pull/560

N21-881 Add videoconference2 to ingress fix

---

ansible/group_vars/develop/cfg.yml
ansible/group_vars/production/cfg.yml
ansible/group_vars/reference/cfg.yml

Enhance CSP-configuration to prevent ClickJacking attacks.
Ticket [BC-4422](https://ticketsystem.dbildungscloud.de/browse/BC-4422)
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3231

BC-4422 - Whitelist frame ancestors

---

.github/workflows/clean.yml
.github/workflows/clean_workflow.yml

https://ticketsystem.dbildungscloud.de/browse/BC-4530

bc-4530 fixup clean workflow

---

ansible/group_vars/all/x_ingress.yml

https://ticketsystem.dbildungscloud.de/browse/BC-4659

BC-4659 Remove v1 sync endpoint from ingress

---

ansible/group_vars/all/config.yml
ansible/group_vars/develop/cfg.yml

- disable columboard for all exclude dev
- revert #574
https://ticketsystem.dbildungscloud.de/browse/BC-4708

BC-4708 - disable columboard for all exclude dev

---

ansible/group_vars/all/config.yml
ansible/group_vars/develop/cfg.yml

Enable the column board for all instances, as the board shall be released with release 32.2.
https://ticketsystem.dbildungscloud.de/browse/BC-4767

BC-4767 - Enable new column board for all instances

---

ansible/group_vars/all/config.yml
ansible/group_vars/all/x_ingress.yml

BC-4737
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4316
https://github.com/hpi-schul-cloud/nuxt-client/pull/2725
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3260
- delete complete task card module from code
- backend and frontend 
- delete mongo collections 
- delete seed data
- delete permissions with prefix TASK_CARD_*** from code, seed and production db
- delete implementation of course endpoint only used for task-card BC-3691
- delete implementation of task filter for assigned users to legacy task BC-3411
- delete implementation of task assignments for legacy task BC-2393

BC-4737 - Remove users property from legacy task clean up task card in general

---

ansible/host_vars/prod-nbc/cfg.yml
ansible/host_vars/ref-nbc/cfg.yml

Activates outdated users feature for nbc on ref/staging and prod
https://ticketsystem.dbildungscloud.de/browse/N21-1168

N21-1168 activate outdated users feature

---

ansible/group_vars/all/x_ingress.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-4352
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4257
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2730

BC-4352 - add ingress for file storage preview

---

ansible/group_vars/all/x_ingress.yml

BC-4786
#hpi-schul-cloud/schulcloud-server/pull/4322
#hpi-schul-cloud/nuxt-client/pull/2755

BC-4786 - add route to ingress

---

ansible/group_vars/all/config.yml
ansible/group_vars/develop/cfg.yml

BC-4966
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4359
https://github.com/hpi-schul-cloud/nuxt-client/pull/2772

BC-4966 - add feature flag for board submissions

---

ansible/group_vars/default/instance_cfg.yml

https://ticketsystem.dbildungscloud.de/browse/BC-3175
This PR sets a custom presentation in the BBB.
`VIDEOCONFERENCE_DEFAULT_PRESENTATION` has been added in the Ansible group vars for the `default`  instances group.
No new repos, packages etc.
No UI changes in terms of the GUI. Only the content of the BBB presentation will be changed for the dBC (default) instances.

BC-3175 - add custom presentation for the dBC BBB

---

ansible/host_vars/prod-nbc/cfg.yml
ansible/host_vars/ref-nbc/cfg.yml

Activates ldap sync feature on ref / stage and prod. This feature allows to activate the ldap sync during the user login migration.
https://ticketsystem.dbildungscloud.de/browse/N21-1260
FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION=true

N21-1260 activate ldap sync during migration feature

---

.github/workflows/rollout.yml

Forgot to rename the hoststage from dev to develop. This lead to it that the instance has no access to the group vars. 

OPS-4953-move-test-clusters-to-dev-fix-2

---

ansible/host_vars/prod-nbc/cfg.yml
ansible/host_vars/ref-nbc/cfg.yml

Deactivates ctl feature for nbc in ref/stage and prod

N21-1270 deactivate ctl feature

---

ansible/host_vars/prod-nbc/cfg.yml
ansible/host_vars/ref-nbc/cfg.yml

Activates ldap sync during user login migration
https://ticketsystem.dbildungscloud.de/browse/N21-1286
FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION=true

N21-1286 activate ldap sync during user login migration

---

ansible/host_vars/prod-nbc/cfg.yml

ldap sync during user login migration
N21-1286 

N21-1286 - deactivate feature flag for production nbc

---

ansible/roles/erwin-idm/templates/ingress.yml.j2
ansible/roles/hydra/templates/ingress.yml.j2
ansible/roles/ingress/templates/ingress.yml.j2
ansible/roles/libreoffice/templates/ingress.yml.j2
ansible/roles/oidcmock/templates/ingress.yml.j2
ansible/roles/rocketchat/templates/ingress.yml.j2
ansible/roles/storage/templates/ingress.yml.j2

Chance how the ingress is selected in accord to the ingess definitiv from kubernetes. Remove the old label and Set it to the spec field
https://ticketsystem.dbildungscloud.de/browse/BC-5163

BC-5163 - ingess class set

---

ansible/roles/erwin-idm/templates/ingress.yml.j2
ansible/roles/hydra/templates/ingress.yml.j2
ansible/roles/libreoffice/templates/ingress.yml.j2
ansible/roles/oidcmock/templates/ingress.yml.j2
ansible/roles/rocketchat/templates/ingress.yml.j2
ansible/roles/storage/templates/ingress.yml.j2

- change ingress rule pathType from ImplementationSpecific to Prefix
https://ticketsystem.dbildungscloud.de/browse/BC-5197
hpi-schul-cloud/superhero-dashboard#232

BC-5197 - change ingress rule pathType to Prefix

---

ansible/host_vars/prod-nbc/cfg.yml
ansible/host_vars/ref-nbc/cfg.yml

Activates ctl for nbc on ref/stage and prod again
https://ticketsystem.dbildungscloud.de/browse/N21-1307

N21-1307 activate ctl again for ref/stage and prod

---

.github/workflows/clean_workflow.yml

modify test if branch exist for clean workflow
Now we use `git show-ref --quiet --verify refs/remotes/origin//${{ env.git_ref_name }}` for it
https://ticketsystem.dbildungscloud.de/browse/BC-5121

BC-5121 - add git checkout branch to test if branch exist for clean workflow

---

ansible/collections/requirements.yml
ansible/roles/mongodb_query_exporter/tasks/main.yml

Fix Helm add git repo pull
uptade ansible requierements from kubernetes.core to 2.4.0
https://ticketsystem.dbildungscloud.de/browse/BC-5488

BC-5488 - fix helm issue

---

ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-5543

BC-5543 update nginx for 404 backend to 1.25

---

ansible/group_vars/develop/maildrop.yml
ansible/group_vars/infra/maildrop.yml
ansible/group_vars/loadtest/maildrop.yml
ansible/group_vars/production/maildrop.yml
ansible/group_vars/reference/maildrop.yml

https://ticketsystem.dbildungscloud.de/browse/BC-5590

BC-5590 update maildrop to 1.5

---

ansible/group_vars/brb/instance_cfg.yml

The extractoion of the FWU Ingress to an own file create issues as the ingress definition where applied so the ingress definitin move back to his old place.
https://ticketsystem.dbildungscloud.de/browse/BC-5705
hpi-schul-cloud/schulcloud-server#4515

BC-5705 - fix fwu ingress part

---

ansible/host_vars/prod-brb/cfg.yml
ansible/host_vars/prod-nbc/cfg.yml
ansible/host_vars/prod-thr/cfg.yml

Deactivates FEATURE_IDENTITY_MANAGEMENT_STORE_ENABLED flag for prod-nbc, prod-brb and prod-thr, since migration job did not run properly. This would cause Keycloak log flooding.

BC-4887 disable keycloak

---

.github/workflows/host.yml
ansible/group_vars/all/git_repos.yml

Additionally to https://github.com/hpi-schul-cloud/dof_app_deploy/pull/689 the new ansible variables need to be set in prod and ref as well.
BC-5405

BC-5405 - Prod_Ref Metadata on k8s ressources

---

.github/workflows/host.yml

fix char error for BRANCH_NAME vars at yaml
https://ticketsystem.dbildungscloud.de/browse/BC-5854

BC-5854 - fix char error for BRANCH_NAME vars at yaml

---

.github/workflows/host.yml

add DOF_APP_DEPLOY_BRANCH_NAME to the rollout
- https://ticketsystem.dbildungscloud.de/browse/BC-5856

BC-5856 - add DOF_APP_DEPLOY_BRANCH_NAME to the rollout

---

ansible/group_vars/all/config.yml

https://ticketsystem.dbildungscloud.de/browse/N21-1505
https://github.com/hpi-schul-cloud/nuxt-client/pull/2924
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4574
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3353

N21-1505 Prevent deletion of global systems

---

ansible/roles/namespace-activator-scaled-objects/defaults/main.yml

since it is not guranteed that it will word when restarted to have access to its pv
https://ticketsystem.dbildungscloud.de/browse/BC-5884

BC-5884 removed redis as a scalable object

---

ansible/group_vars/all/ingress_cfg.yml
ansible/roles/erwin-idm/templates/ingress.yml.j2
ansible/roles/hydra/templates/ingress.yml.j2
ansible/roles/ingress/templates/ingress.yml.j2
ansible/roles/libreoffice/templates/ingress.yml.j2
ansible/roles/oidcmock/templates/ingress.yml.j2
ansible/roles/rocketchat/templates/ingress.yml.j2
ansible/roles/storage/templates/ingress.yml.j2

To improve the situation that one nginx ingress class can't handle our ingress definitions in less then 30 seconds.
We prepared to split the ingress to ingress classes for each tenant.
- hpi-schul-cloud/schulcloud-server#4593
- hpi-schul-cloud/superhero-dashboard#236
- hpi-schul-cloud/tldraw-client#26
- https://ticketsystem.dbildungscloud.de/browse/BC-5801

BC-5801 - Ingress class configurable

---

ansible/collections/requirements.yml
ansible/roles/mongodb_query_exporter/tasks/main.yml

This reverts commit c46f82fb7c153f79c892fcfc738137181cafc336.
https://ticketsystem.dbildungscloud.de/browse/BC-5975

Revert "BC-5488 - fix helm issue (#660)"

---

ansible/group_vars/develop/dof_postgresql.yml

https://ticketsystem.dbildungscloud.de/browse/BC-1943

BC-1943 update postgres to 15.5

---

ansible/group_vars/develop/maildrop.yml
ansible/group_vars/infra/maildrop.yml
ansible/group_vars/loadtest/maildrop.yml
ansible/group_vars/production/maildrop.yml
ansible/group_vars/reference/maildrop.yml
ansible/roles/maildrop/templates/deployment.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-6023

BC-6023 add liveness prove to mail drop

---

.github/workflows/clean_workflow.yml

Fix double delete and an } whas not need
https://ticketsystem.dbildungscloud.de/browse/BC-6013

BC-6013 - fixe delete not use namespaces

---

ansible/group_vars/all/config.yml

Please remove the multi-message-banner with the following text:
"Nehmen Sie an unserer Zufriedenheitsumfrage teil und helfen Sie uns, die Cloud zu verbessern. Hier geht’s zur Befragung."
**Banner should be removed around the 19.12. (26.12. the latest)**
https://ticketsystem.dbildungscloud.de/browse/BC-5966
Link to deployment : https://default-bc-5966-disable-survey-banner.cd.dbildungscloud.dev/

BC-5966 - Delete Information about user survey (for teachers only) in multi-message-banner

---

ansible/group_vars/all/config.yml

enable board link element

---

ansible/group_vars/all/config.yml

BC-5981 - set default dashboard banner value to true

---

.github/workflows/clean.yml
.github/workflows/clean_branches.yml
.github/workflows/clean_workflow.yml
.github/workflows/deploy.yml
.github/workflows/push.yml

...  as it was superseded by the namespace (de)activator logic
https://ticketsystem.dbildungscloud.de/browse/BC-6032

BC-6032 remove dof_bingo

---

README.md

https://ticketsystem.dbildungscloud.de/browse/BC-5754

BC-5754 namespace (de)activation documentation

---

ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/dbc/instance_cfg.yml
ansible/group_vars/nbc/instance_cfg.yml
ansible/group_vars/thr/instance_cfg.yml
ansible/roles/ingress/templates/ingress.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-6088

BC-6088 fix activator redirect

---

ansible/roles/namespace-activator-scaled-objects/defaults/main.yml
sc-common/namespace-activator/base/app.yml
sc-common/namespace-activator/overlays/brb/kustomization.yaml
sc-common/namespace-activator/overlays/dbc/kustomization.yaml
sc-common/namespace-activator/overlays/nbc/kustomization.yaml
sc-common/namespace-activator/overlays/thr/kustomization.yaml

https://ticketsystem.dbildungscloud.de/browse/BC-5754

BC-5754 update to namespace (de)activator 2

---

ansible/roles/rocketchat/templates/fixup-job.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-6206

BC-6206 changed the imagePullPolicy in fixup-rocketchat-job

---

.github/workflows/clean_workflow.yml
.github/workflows/deploy.yml
ansible/hosts

Add TSP Dev Deployment to TSP Dev Cluster
Also add the deletetion of the deployed namespace after no branches for it exist at github
- https://ticketsystem.dbildungscloud.de/browse/BC-5457 
- Login: https://test.schulportal-thueringen.de/cas/login?service=https%3A%2F%2Fbc-5457-thr-deployment.thr.dbildungscloud.dev%2Ftsp-login
- http://bc-5457-thr-deployment.thr.dbildungscloud.de

BC-5457 - add thr Deployment

---

ansible/roles/clamav/templates/deployment.yml.j2
ansible/roles/dof_etherpad/templates/deployment.yml.j2
ansible/roles/dof_etherpad_nginx/templates/deployment.yml.j2
ansible/roles/dof_mailcatcher/templates/deployment.yml.j2
ansible/roles/dof_mongo/templates/deployment.yml.j2
ansible/roles/dof_postgresql/templates/deployment.yml.j2
ansible/roles/dof_redis/templates/deployment.yml.j2
ansible/roles/erwin-idm/templates/deployment.yml.j2
ansible/roles/hydra/templates/deployment.yml.j2
ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2
ansible/roles/libreoffice/templates/deployment.yml.j2
ansible/roles/maildrop/templates/deployment.yml.j2
ansible/roles/oidcmock/templates/deployment.yml.j2
ansible/roles/rocketchat/templates/deployment.yml.j2
ansible/roles/rocketchat/templates/fixup-job.yml.j2
ansible/roles/storage/templates/deployment.yml.j2

Remove git.branch from pod templates, this cause not necessary pods restarts by updates pod templates
- https://ticketsystem.dbildungscloud.de/browse/BC-6301

BC-6301 - remvoe git.branch from pod templates

---

ansible/group_vars/all/config.yml
ansible/group_vars/nbc/instance_cfg.yml
ansible/host_vars/prod-nbc/cfg.yml

Adds schulconnex envs for nbc
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4707
- https://ticketsystem.dbildungscloud.de/browse/N21-1630
- https://ticketsystem.dbildungscloud.de/browse/BC-6366

N21-1630 adds SCHULCONNEX envs for nbc

---

ansible/group_vars/brb/instance_cfg.yml
ansible/host_vars/prod-brb/cfg.yml
ansible/host_vars/ref-brb/cfg.yml

https://ticketsystem.dbildungscloud.de/browse/OPS-5839

OPS-5839 Added bettermarks proxy urls for brandenburg

---

README.md

BC-6399 document on how to add secrets

---

ansible/group_vars/all/config.yml

BC-5252
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4755
https://github.com/hpi-schul-cloud/nuxt-client/pull/3077

BC-5252 - remove old course share env

---

ansible/host_vars/prod-dbc/cfg.yml
ansible/host_vars/prod-dbc/with.yml
ansible/host_vars/ref-dbc/cfg.yml
ansible/host_vars/ref-dbc/with.yml

Enabling tldraw functionalities for dbc staging and prod.
https://ticketsystem.dbildungscloud.de/browse/BC-6646

BC-6646 Enable tldraw for dbc production and staging instances

---

ansible/group_vars/all/mongodb_query_exporter.yaml

https://ticketsystem.dbildungscloud.de/browse/BC-6705

BC-6405 add metric for total number of drawing elements in boards

---

ansible/host_vars/thr_host/cfg.yml

OPS-5793 add base URL

---

ansible/host_vars/prod-thr/cfg.yml

Activates FEATURE_IDENTITY_MANAGEMENT_STORE_ENABLED flag for prod-thr.
https://ticketsystem.dbildungscloud.de/browse/BC-4887

BC-4887 Enable keycloak sync on prod THR

---

ansible/group_vars/all/config.yml
ansible/group_vars/all/x_ingress.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-5334
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4882
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3436
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3183

BC-5334 - remove unused API endpoint configurations

---

ansible/group_vars/all/config.yml

Add feature flag for column board web sockets feature
Jira: BC-6850
Vue-Client: https://github.com/hpi-schul-cloud/nuxt-client/pull/3194
Server: https://github.com/hpi-schul-cloud/schulcloud-server/pull/4924

BC-6850 - Implement socket API for the column board

---

ansible/group_vars/develop/postgres.yml

Add "release_" prefix for postgres if namespace starts with a number.

BC-7297-fix-postgres-init

---

ansible/roles/namespace-activator-scaled-objects/defaults/main.yml

An addition to: https://github.com/hpi-schul-cloud/dof_app_deploy/pull/869#issue-2298050061

EW-834 added common cartridge deployment into scaled object

---

ansible/group_vars/dbc/instance_cfg.yml
ansible/group_vars/nbc/instance_cfg.yml
ansible/group_vars/thr/instance_cfg.yml

To provide further information for our users (teachers and admins) we want to display the blue status bar again.
Visibility should be set for admins and teachers only.
BC-6916
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3452
- adding config for dBC, THR and NBC

BC-6916 - SJW display blue status bar (dBC, NBC, TSC)

---

ansible/host_vars/thr_host/cfg.yml

EW-944 Switch to IDM accounts on THR dev

---

ansible/roles/mongodb_query_exporter/defaults/main.yaml

https://ticketsystem.dbildungscloud.de/browse/BC-7589

BC-5789 update mongodb query exporter

---

ansible/group_vars/all/config.yml

BC-6930
https://github.com/hpi-schul-cloud/nuxt-client/pull/3304
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3469
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5088

BC-6930 - set default for enabling new layout to true

---

ansible/group_vars/all/config.yml

Reducing wait time for blocked login.
BC-6273

BC-6273 - Reduce failed login waiting period from 15 to 5 seconds

---

ansible/host_vars/thr_host/cfg.yml

Reverts hpi-schul-cloud/dof_app_deploy#887

Revert "EW-944 Switch to IDM accounts on THR dev"

---

ansible/roles/hydra/templates/job.yml.j2

Fixes hydra-svc load balancing through giving the job another label then the pod.
We had a zombie pod of a hydra migration job running in nbc main. This pod had the same label as the hydra deployment pod. Because the hydra-svc service does its load balancing via the label, it sometimes addressed the job pod and sometimes the deployment pod. The job pod refused the connection, which then led to an error in the UI.
- https://ticketsystem.dbildungscloud.de/browse/N21-2079

N21-2079 changes label of hydra migration job

---

ansible/host_vars/ref-nbc/cfg.yml

This PR fixes url for moin.schule lizenz-info in ref.
- https://ticketsystem.dbildungscloud.de/browse/N21-2091

N21-2091 fixes url for moin.schule lizenz-info in ref

---

ansible/roles/erwin-idm/tasks/main.yml
ansible/roles/erwin-idm/templates/configmap.yml.j2
ansible/roles/erwin-idm/templates/ingress.yml.j2

- https://ticketsystem.dbildungscloud.de/browse/EW-982

EW-982: Fix erwin idm on staging.

---

ansible/group_vars/all/config.yml
ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/nbc/instance_cfg.yml

- adjusting env var for dashboard banner with bettermarks note
BC-7480
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3498

BC-7480 - Display Dashboard banner SC BB: Bettermarks and course overview

---

ansible/group_vars/all/config.yml
ansible/host_vars/nbc_host/cfg.yml

- https://ticketsystem.dbildungscloud.de/browse/N21-2100
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5168
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3348

N21-2100 AI Features

---

ansible/group_vars/all/config.yml
ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/dbc/instance_cfg.yml
ansible/group_vars/nbc/instance_cfg.yml
ansible/group_vars/thr/instance_cfg.yml

Changing the location of the video training material to a separate federal state location for each state.
For that a new env var `TRAINING_URL` is introduced.
+ editing `ACCESSIBILITY_REPORT_EMAIL` for dBC (currently not visible, just for keeping it up to date)
BC-7700
BC-7701
BC-7702
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3499
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5170
https://github.com/hpi-schul-cloud/nuxt-client/pull/3350

BC-7700 BC-7701 BC-7702 - replacing LC links on platform

---

sc-common/namespace-activator/base/app.yml

https://ticketsystem.dbildungscloud.de/browse/BC-7892

BC-7892 update namespace-activator

---

sc-common/namespace-activator/base/app.yml

https://ticketsystem.dbildungscloud.de/browse/BC-6618

BC-6618 remove stale namespaces automatically

---

ansible/roles/hydra/defaults/main.yaml

[BC-7876](https://ticketsystem.dbildungscloud.de/browse/BC-7876)
see also https://github.com/ory/hydra/issues/2911

BC-7876 update to hydra 2.2.0

---

.github/workflows/clean_workflow.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-7912

BC-7912 - split clean to more jobs

---

.github/workflows/clean_workflow.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-7912

BC-7912 - fix missing matrix at clean workflow

---

ansible/roles/hydra/templates/configmap_file_init_db.yml.j2

- https://ticketsystem.dbildungscloud.de/browse/BC-7952

BC-7952 - fix hydra db init aka migrate sql

---

ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/dbc/instance_cfg.yml

The banner for the change of school year is to be removed for all users in SC BB and dBC again.
instance: SC BB and DBC only
The banner should be removed in prod with the release 32.44  on 18.09.2024
BC-7856

BC-7856 - SC BB/dBC: Remove Banner for change of school year on 18.09.24

---

ansible/host_vars/prod-brb/cfg.yml
ansible/host_vars/prod-dbc/cfg.yml

disable keycloak

---

ansible/group_vars/all/config.yml

https://ticketsystem.dbildungscloud.de/browse/BC-3289
https://github.com/hpi-schul-cloud/nuxt-client/pull/3388

BC-3289 removed now unused API_URL variable

---

ansible/group_vars/all/x_ingress.yml

we want to have an actual route for the (column-) board
BC-7839
https://github.com/hpi-schul-cloud/nuxt-client/pull/3389
- editing `/rooms/:boardId/board => /boards/:boardId`

BC-7839 - Change routing for board

---

ansible/group_vars/brb/instance_cfg.yml

Disable Dashboard Banner with release 32.45
BC-7546

BC-7546 - Disable Dashboard banner SC BB: Bettermarks and course overview

---

sc-common/namespace-activator/base/app.yml

to remove the deactivation feature

update namespace activator to 2.5

---

ansible/roles/namespace-activator-scaled-objects/defaults/main.yml
ansible/roles/namespace-activator-scaled-objects/tasks/main.yml
ansible/roles/namespace-activator-scaled-objects/templates/scaled-object.yml.j2

BC-8110 scale valkey to 0 for namespace deactivation

---

ansible/group_vars/all/instance_config_all.yml

- hpi-schul-cloud/schulcloud-server#5249
- https://ticketsystem.dbildungscloud.de/browse/BC-8123

BC-8123 - Nest Log level error

---

ansible/group_vars/all/instance_config_all.yml

This reverts commit 360bd87dc2a065d7b6190f352fe4ef90c8f423a0.
https://ticketsystem.dbildungscloud.de/browse/BC-8290

BC-8290 Revert "BC-8123 - Nest Log level error (#975)"

---

ansible/host_vars/prod-nbc/cfg.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-8328
- #1009 1009

BC-8328 - license check also on prod nbc off

---

ansible/roles/mongodb_query_exporter/templates/values.yml.j2

- https://ticketsystem.dbildungscloud.de/browse/BC-8360

BC-8360 - move metics from mongo quey exportor to longterm 

---

ansible/roles/mongodb_query_exporter/templates/values.yml.j2

- hpi-schul-cloud/dof_app_deploy#1014
- https://ticketsystem.dbildungscloud.de/browse/BC-8360

BC-8360 - fix double constLabels

---

ansible/roles/mongodb_query_exporter/templates/values.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-8360

BC-8360 added longterm: true to users_without_accounts

---

ansible/group_vars/all/config.yml

BC-8499 set WITH_TLDRAW2 explicitly to true as a temporary measure

---

ansible/group_vars/all/config.yml

…easure (#1046)"
This reverts commit 71c9c7bbfd4ea2d64fb901c8a8bd29467b2a0e0e.
BC-8499

Revert "BC-8499 set WITH_TLDRAW2 explicitly to true as a temporary

---

ansible/group_vars/reference/mongodb_query_exporter.yaml
ansible/host_vars/ref-audit/mongodb_query_exporter.yaml
ansible/host_vars/ref-brb/mongodb_query_exporter.yaml
ansible/host_vars/ref-dbc/mongodb_query_exporter.yaml
ansible/host_vars/ref-nbc/mongodb_query_exporter.yaml
ansible/host_vars/ref-thr/mongodb_query_exporter.yaml

Updates the MongoDB database name for the Query Exporter.
After the MongoDB migration the database names change from `staging_<tenant>_schulcloud` (`staging_schulcloud` for hpi) to `<tenant>_schulcloud`.
Only affects staging/reference, the names stay the same on prod.
[OPS-6866](https://ticketsystem.dbildungscloud.de/browse/OPS-6866)

BC-8506-change-mongo-queryexporter-db-name

---

.github/workflows/deploy_dev.yml
.github/workflows/host.yml
.github/workflows/test.yml

BC-8523 update python to 3.13

---

ansible/host_vars/ref-audit/cfg.yml

[TICKET](https://ticketsystem.dbildungscloud.de/browse/BC-8527)

BC-8527 - add feature flag to ref-audit cfg.yml

---

ansible/group_vars/all/x_ingress.yml
ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/dbc/instance_cfg.yml
ansible/group_vars/thr/instance_cfg.yml

https://ticketsystem.dbildungscloud.de/browse/BC-8221
https://github.com/hpi-schul-cloud/nuxt-client/pull/3483
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3551

BC-8221 pull default bbb presentation from nuxt

---

ansible/group_vars/all/config.yml

Users with groups containing fewer than 1000 members are still experiencing login issues. To address this, we are halving the group size limit to further reduce timeouts.
https://ticketsystem.dbildungscloud.de/browse/BC-8614

BC-8614 Reduce NBC group size limit to mitigate timeouts

---

ansible/group_vars/thr/instance_cfg.yml

BC-8616 set STUDENT_TEAM_CREATION to opt-in

---

sc-common/namespace-activator/base/app.yml

https://ticketsystem.dbildungscloud.de/browse/BC-8620

BC-8620 add longterm label and update namespace activator

---

ansible/host_vars/prod-nbc/smtp.yml

SVS contact form
- adapt text and options
- replace support mail adresses for nbc
BC-8608
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3552

BC-8608 - adjust contact form

---

ansible/group_vars/all/config.yml

BC-8774 changed PROVISIONING_SCHULCONNEX_GROUP_USERS_LIMIT to 400
https://ticketsystem.dbildungscloud.de/browse/BC-8774

BC-8774 changed PROVISIONING_SCHULCONNEX_GROUP_USERS_LIMIT to 400

---

ansible/group_vars/all/config.yml

only variables that are used in config/docker/nginx.conf.template in nuxt-client do have an effect and those deleted here are not.
https://ticketsystem.dbildungscloud.de/browse/BC-8822

BC-8822 remove unused nuxt env vars

---

ansible/roles/clamav/defaults/main.yml

https://ticketsystem.dbildungscloud.de/browse/BC-8826

BC-8826 update clamav to 1.4.2

---

ansible/group_vars/all/config.yml
ansible/group_vars/production/cfg.yml

BC-8924
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5495

BC-8924 Remove env var ES_API_V7

---

sc-common/namespace-activator/base/app.yml

https://ticketsystem.dbildungscloud.de/browse/BC-9139

BC-9139 update namespace activator

---

ansible/roles/sys/tasks/main.yml
ansible/roles/sys/templates/deny-all-networkpolicy.yml.j2
ansible/roles/sys/templates/networkpolicy.yml.j2

Add network policies
- https://ticketsystem.dbildungscloud.de/browse/BC-9078
- https://bc-9078-netpol.dbc.dbildungscloud.dev
- https://bc-9078-netpol.nbc.dbildungscloud.dev
- https://bc-9078-netpol.dbc.dbildungscloud.dev

BC-9078 - add network policies

---

ansible/group_vars/all/config.yml
ansible/group_vars/nbc/instance_cfg.yml

- https://ticketsystem.dbildungscloud.de/browse/BC-9594
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3693

BC-9594 - Setting Default Info Link

---

ansible/roles/maildrop/defaults/main.yaml

https://ticketsystem.dbildungscloud.de/browse/BC-9715

BC-9715 update mail-drop to 2.2

---

ansible/group_vars/all/misc.yml

- extend the h5p libraries list
- https://ticketsystem.dbildungscloud.de/browse/N21-2580
- misc.yml

N21-2580 add new h5p libraries

---

sc-common/telepresence-traffic-manager/values.yaml

https://ticketsystem.dbildungscloud.de/browse/BC-10038?jql=text%20~%20%22telepresence%22

BC-10038 fixup ip ranges

---

.github/workflows/deploy.yml
.github/workflows/deploy_dev.yml
.github/workflows/host.yml
ansible/collections/requirements.yml
ansible/roles/dof_rabbitmq/tasks/main.yml
ansible/roles/namespace-activator-scaled-objects/defaults/main.yml

also caching ansible collection and apt package python3-kubernetes via awalsh128/cache-apt-pkgs-action
speeds up dev deployments per task from 30s - 90s for each deploy job.
https://ticketsystem.dbildungscloud.de/browse/BC-10103

BC-10103 speed up dev deployments by seperating keda and helm chart tasks

---

ansible/group_vars/all/config.yml

BC-9046 - introduce JWT_HTTP_ONLY

---

ansible/roles/session-valkey/templates/values.yml.j2

Update Bitnami image regestry to bitnami docker image legacy regestry
- hpi-schul-cloud/tldraw-server#74
- https://ticketsystem.dbildungscloud.de/browse/BC-10408

BC-10408 - DOPS-179 - change bitname images for valkey to bitnamilegacy images

---

.github/workflows/deploy.yml

this uses the safe branch name, to avoid issues like this
```
TASK [dof_mailcatcher : Deployment] ********************************************
fatal: [dbc_host]: FAILED! => {"changed": false, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Deployment.apps \\\\\"mailcatcher-deployment\\\\\" is invalid: metadata.labels: Invalid value: \\\\\"dependabot.github_actions.dot-github.workflows.SonarSource.sonarqube-scan-action-5.3.1\\\\\": must be no more than 63 characters\",\"reason\":\"Invalid\",\"details\":{\"name\":\"mailcatcher-deployment\",\"group\":\"apps\",\"kind\":\"Deployment\",\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: …
```

fixup branch length limitation for labels

---

ansible/roles/dof_mongo/templates/svc-monitor.yml.j2
ansible/roles/dof_rabbitmq/templates/rabbitmq-svc-monitor.yml.j2
ansible/roles/erwin-idm/templates/erwinidm-svc-monitor.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-10601

BC-10601 fixup label selectors in -> In

---

ansible/group_vars/brb/instance_cfg.yml
ansible/group_vars/dbc/instance_cfg.yml

Remove banners for changing school year for brb and dbc.
BC-9811

BC-9811 - SJW: Remove Banners (SCBB, dBC)

---

ansible/roles/collabora-office/templates/ingress.yml.j2
ansible/roles/dof_mailcatcher/templates/deployment.yml.j2
ansible/roles/erwin-idm/templates/admin-certificate.yml.j2
ansible/roles/erwin-idm/templates/admin-ingress.yml.j2
ansible/roles/erwin-idm/templates/ingress.yml.j2
ansible/roles/hydra/templates/ingress.yml.j2
ansible/roles/ingress/templates/ingress.yml.j2
ansible/roles/libreoffice/templates/ingress.yml.j2
ansible/roles/maildrop/templates/deployment.yml.j2
ansible/roles/oidcmock/templates/ingress.yml.j2
ansible/roles/rocketchat/templates/ingress.yml.j2
ansible/roles/storage/templates/ingress.yml.j2

https://ticketsystem.dbildungscloud.de/browse/BC-10615
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5884
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3697
https://github.com/hpi-schul-cloud/nuxt-client/pull/3886
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/325
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1249

BC-10615 adopt ansible migration aids
